version: '3.3'
services:
  web:
    image: tubes-1:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./src/app:/var/www/app
      - ./src/public:/var/www/html
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      -  ./db:/var/lib/postgres/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8081:80


networks:
  web-postgres:
    driver: bridge