version: '3.3'
services:
  notflix-app:
    image: tubes-1:latest
    build: .
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./src/app:/var/www/app
      - ./src/public:/var/www/html
    depends_on:
      php-db:
        condition: service_healthy
  php-db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5431:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10
      timeout: 5s
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8081:80
