version: '3.3'
services:
  web:
    image: tubes-1:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./src/app:/var/www/app
      - ./src/public:/var/www/html
    networks:
      - web-postgres
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - 5431:5432
    volumes:
      -  ./db:/var/lib/postgres/data
      - ./migrations:/docker-entrypoint-initdb.d/01_sample.sql
    networks:
      - web-postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8081:80


networks:
  web-postgres:
    driver: bridge